// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfKeTbJFkl2XP-BVhHe1NEwdLSuwkg1Tg',
    appId: '1:349459893976:android:ac6aeacf91cdbd77e211ad',
    messagingSenderId: '349459893976',
    projectId: 'first-flutter-app-jcruizg',
    storageBucket: 'first-flutter-app-jcruizg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSP94Z-6AE6GMvbDC-Hoj3iY2HNk1oo5I',
    appId: '1:349459893976:ios:55a7e1213f13c152e211ad',
    messagingSenderId: '349459893976',
    projectId: 'first-flutter-app-jcruizg',
    storageBucket: 'first-flutter-app-jcruizg.appspot.com',
    iosClientId: '349459893976-j9a8o6qn8086pm5o1h6h6m1bpar4tne2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirstProject',
  );
}
